version: '3'
services:
  mysql:
    image: mysql:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DATABASE
    ports:
      - "3307:3306"
    volumes:
      - ./sql-script:/docker-entrypoint-initdb.d
    

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql