client_config_backend: settings
client_config:
  client_id: 364195420820-nf9tjfmqfkn25d94i54vtu4rmggbd5bb.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive